apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  serviceAccountName: {{ .Values.appName }}
{{ if .Values.initContainers.enabled }}
  volumes:
    - name: config
      emptyDir:
        sizeLimit: 5Mi
  initContainers:
    - name: aws-param
      image: 492681564023.dkr.ecr.us-east-1.amazonaws.com/expense_parameter_init_container:{{ .Values.initContainers.imageVersion }}
      env:
        - name: INPUT
          value: {{ .Values.initContainers.INPUT }}
      volumeMounts:
      - mountPath: /config
        name: config
  containers:
    - name: {{ .Values.appName }}
      image: 492681564023.dkr.ecr.us-east-1.amazonaws.com/{{ .Values.appName }}:{{ .Values.appVersion }}
      volumeMounts:
      - mountPath: /config
        name: config
{{ else }}
  containers:
    - name: {{ .Values.appName }}
      image: 492681564023.dkr.ecr.us-east-1.amazonaws.com/{{ .Values.appName }}:{{ .Values.appVersion }}
{{ end }}