apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  serviceAccountName: {{ .Values.appName }}
  containers:
    - name: {{ .Values.appName }}
      image: 492681564023.dkr.ecr.us-east-1.amazonaws.com/{{ .Values.appName }}:{{ .Values.appVersion }}